### ISSUE TITLE
Can't run Final burn alpha rom (zip files) with Yava

### ISSUE THREAD

**Issue by Kvaell** [Beluki/Yava#1]
Hello Sir,

Thank you for your great software, It's really the only one launcher that allows to use any emulator without using retroarch that is far from my taste.

Today I encountered a problem, it seems that Fba cannot read zip files from Yava.

Do you have any idea how to fix this issue?

BTW I have 3 others questions;

1. Can you explain what are the use of:

parameters = --batch --exec "%FILEPATH%"
--nogui "%FILEPATH%"

2. Is it possible to add several rom path to the same emulator (or to allow Yava to see the sub directories inside the main one) without adding a complete emulator setting again in the same ini file?

3. Is it possible to allow Yava to detect x-input gamepad not to have to use a mouse?

Thanks for you help.

Regards

![yava no fba](https://user-images.githubusercontent.com/27021339/44990758-5c189100-af92-11e8-9166-40bc46622683.png)

**Comment by Beluki** [comment]
Hello

 

I am sorry I cant help you, Beluki has died two years ago. Lung cancer.

 

Marisa


Sent: Monday, September 03, 2018 at 3:46 PM

**Comment by Kvaell** [comment]
Oh…. I'm sorry about that.

Best regards
